[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://178.18.240.206:5000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/_redirects"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.@(js|css|jpg|jpeg|gif|png|svg|woff|woff2|ttf|eot)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

